### PR TITLE
Some minor corrections

### PR DESCRIPTION
**Pull request by Matthieu-Malyga**
Hi, 

just a little change in the JavaScript board init with zeros.

### CODE REVIEW

**Review by unbug — APPROVED** [review]
Thanks @Matthieu-Malyga, if you don't have any new update, I shall merge it later :)

**Comment by unbug** [comment]
Good catch @Matthieu-Malyga , let me know when the PR ready to merge :)

**Comment by Matthieu-Malyga** [comment]
I spotted some tiny corrections (one actually so far). I'm reading (translating actually : that's why I've the right reading speed to spot little things :P) till the end of the chapter and let you know ;)

**Comment by unbug** [comment]
Take your time :)

**Comment by Matthieu-Malyga** [comment]
That should be it.

**Comment by unbug** [comment]
@Matthieu-Malyga So, shall I merge the changes?

**Comment by Matthieu-Malyga** [comment]
Yes please go ahead.

**Pull request merged**
